server:
  port: 8002

spring:
  application:
    name: eureka8002

eureka:
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 3000 # 设置服务的清理间隔(若有服务3s内没有发送心跳给eureka，则会移除它)，(单位毫秒: 默认是60 * 1000)
  instance:
    # 服务实例的名称
    hostname: eureka8002

  # 添加eureka 客户端服务注册配置, 注册中心暴露这个地址进行注册，客户端就是通过此配置来关联上对应的eureka的
  client:
    service-url:
      defaultZone: http://eureka8000.com:8000/eureka, http://eureka8001.com:8001/eureka
    # 服务端不注册，即当前的eureka不注册到自己身上
    register-with-eureka: false



