spring:
  profiles:
    include:
      - constants

eureka:
  server:
    enable-self-preservation: false # 关闭自我保护机制
    eviction-interval-timer-in-ms: 3000 # 设置服务的清理间隔(若有服务3s内没有发送心跳给eureka，则会移除它)，(单位毫秒: 默认是60 * 1000)
  instance:
    # 服务实例的名称
    hostname: ${customize.wfw.registrationCenter[0].hostname}
  client:
    # 服务端不注册，即当前的eureka不注册到自己身上, 不添加此配置的话，可能会抛出
    # com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
    # 的异常
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${customize.wfw.registrationCenter[0].url}